import unittest

from tests._web_support import WebTestCase


class WebStaticAssetTests(WebTestCase):
    def test_root_static_assets_are_served(self):
        expected = {
            "/static/splash.jpg": "image/jpeg",
            "/static/default-pfp.png": "image/png",
            "/static/app.css": "text/css",
            "/static/app.js": "text/javascript",
            "/static/js/context.js": "text/javascript",
            "/static/js/settings.js": "text/javascript",
            "/static/js/chat.js": "text/javascript",
            "/static/js/audio.js": "text/javascript",
            "/static/js/device-control.js": "text/javascript",
            "/static/js/motion-control.js": "text/javascript",
            "/static/js/motion/feedback-controls.js": "text/javascript",
            "/static/js/motion/pause-controls.js": "text/javascript",
            "/static/js/motion/pattern-list.js": "text/javascript",
            "/static/js/motion/sequence-log.js": "text/javascript",
            "/static/js/motion/training-editor.js": "text/javascript",
            "/static/js/setup.js": "text/javascript",
        }

        for path, mimetype in expected.items():
            with self.subTest(path=path):
                response = self.client.get(path)
                try:
                    self.assertEqual(response.status_code, 200)
                    self.assertEqual(response.mimetype, mimetype)
                    self.assertGreater(len(response.data), 0)
                finally:
                    response.close()

    def test_root_links_frontend_assets(self):
        response = self.client.get("/")
        try:
            page = response.get_data(as_text=True)

            self.assertIn('href="/static/app.css"', page)
            self.assertIn('src="/static/app.js"', page)
            self.assertIn('type="module"', page)
            self.assertIn('id="like-this-move-btn"', page)
            self.assertIn('id="dislike-this-move-btn"', page)
            self.assertIn('id="motion-meter-panel"', page)
            self.assertIn('id="motion-feedback-buttons"', page)
            self.assertIn('id="motion-status-strip"', page)
            self.assertIn('id="motion-sequence-indicator"', page)
            self.assertIn('class="motion-sequence-indicator motion-sequence-log"', page)
            self.assertIn('role="log"', page)
            self.assertIn('id="motion-diagnostics-panel"', page)
            self.assertIn('id="edging-timer" style="display: none;" aria-live="polite"', page)
            self.assertIn('id="ollama-diagnostics-level-select"', page)
            self.assertIn('id="motion-diagnostics-level-select"', page)
            self.assertIn('id="motion-feedback-auto-disable-checkbox"', page)
            self.assertIn('id="toggle-memory-btn"', page)
            self.assertIn("Memories: ON", page)
            self.assertIn('id="pause-resume-btn"', page)
            self.assertLess(page.index('id="pause-resume-btn"'), page.index('id="start-auto-btn"'))
            self.assertIn('Hotkey: Play/Pause media key', page)
            self.assertIn('Hotkey: double-tap Shift', page)
            self.assertIn('Hotkey: Stop media key', page)
            self.assertIn('id="sidebar-motion-indicator"', page)
            self.assertIn('id="handy-cylinder-indicator"', page)
            self.assertNotIn('id="motion-trace-panel"', page)
            self.assertNotIn('id="rhythm-canvas"', page)
            self.assertIn("Preset Modes", page)
            self.assertIn('class="preset-mode-stack"', page)
            self.assertIn("Experimental Modes", page)
            self.assertIn('class="experimental-mode-stack"', page)
            self.assertIn('id="freestyle-mode-btn"', page)
            self.assertIn('Adaptive pattern selection using enabled motion patterns.', page)
            self.assertNotIn('id="freestyle-mode-btn" class="my-button sidebar-button experimental" disabled', page)
            self.assertIn('class="sidebar-stop-section"', page)
            self.assertNotIn("DANGER ZONE", page)
            self.assertNotIn("<style>", page)
            self.assertNotIn("<script>", page)
        finally:
            response.close()

    def test_settings_dialog_contains_device_and_speed_controls(self):
        response = self.client.get("/")
        try:
            page = response.get_data(as_text=True)

            self.assertIn('id="persona-prompt-select"', page)
            self.assertIn('id="save-persona-prompt-btn"', page)
            self.assertIn('data-settings-tab="device"', page)
            self.assertIn('id="settings-tab-device"', page)
            self.assertIn('id="handy-key-input"', page)
            self.assertIn('id="motion-depth-min-slider"', page)
            self.assertIn('id="motion-depth-max-slider"', page)
            self.assertIn('id="motion-speed-min-slider"', page)
            self.assertIn('id="motion-speed-max-slider"', page)
            self.assertIn('id="save-motion-speed-limits"', page)
            self.assertIn('id="motion-backend-select"', page)
            self.assertIn('id="save-motion-backend-btn"', page)
            self.assertIn('id="motion-backend-status"', page)
            self.assertIn('Flexible position/script (experimental)', page)
            self.assertIn('id="allow-llm-edge-freestyle-checkbox"', page)
            self.assertIn('id="allow-llm-edge-chat-checkbox"', page)
            self.assertIn('id="save-llm-edge-permissions-btn"', page)
            self.assertIn('id="motion-pattern-list"', page)
            self.assertIn('id="motion-feedback-history"', page)
            self.assertIn('id="refresh-motion-patterns-btn"', page)
            self.assertIn('id="import-motion-pattern-btn"', page)
            self.assertIn('id="open-motion-training-btn"', page)
            self.assertIn('id="motion-pattern-import-input"', page)
            self.assertIn('id="motion-training-dialog"', page)
            self.assertIn('id="close-motion-training-btn"', page)
            self.assertIn('id="motion-training-status"', page)
            self.assertIn('id="stop-motion-training-btn"', page)
            self.assertIn('id="motion-training-pattern-list"', page)
            self.assertIn('id="motion-training-pattern-title"', page)
            self.assertIn('id="motion-training-original-preview-canvas"', page)
            self.assertIn('id="motion-training-preview-canvas"', page)
            self.assertIn('Original', page)
            self.assertIn('Edited', page)
            self.assertIn('id="motion-transform-smooth-btn"', page)
            self.assertIn('id="motion-transform-harshen-btn"', page)
            self.assertIn('id="motion-training-duration-value"', page)
            self.assertIn('id="motion-training-tempo-value"', page)
            self.assertIn('id="motion-transform-duration-down-btn"', page)
            self.assertIn('id="motion-transform-duration-up-btn"', page)
            self.assertIn('id="motion-transform-tempo-down-btn"', page)
            self.assertIn('id="motion-transform-tempo-up-btn"', page)
            self.assertIn('class="motion-training-arrow motion-training-arrow-down"', page)
            self.assertIn('data-range-step-target="motion-training-range-min"', page)
            self.assertIn('data-range-step-target="motion-training-range-max"', page)
            self.assertIn('id="motion-transform-range-btn"', page)
            self.assertIn('Duration and tempo', page)
            self.assertIn('id="play-motion-training-preview-btn"', page)
            self.assertIn('id="save-motion-training-pattern-btn"', page)
            self.assertIn('id="motion-training-feedback-up"', page)
            self.assertIn('Preview: Flexible position', page)
            self.assertIn('id="app-motion-backend-badge"', page)
            self.assertIn('App motion: HAMP continuous', page)
            self.assertIn('data-settings-tab="advanced"', page)
            self.assertIn('id="settings-tab-advanced"', page)
            self.assertIn('id="reset-settings-btn"', page)
            self.assertIn('id="local-tts-engine-select"', page)
            self.assertIn('value="chatterbox_turbo"', page)
            self.assertIn('id="download-ollama-model-btn"', page)
            self.assertIn('id="refresh-ollama-status-btn"', page)
            self.assertIn('id="download-local-tts-model-button"', page)
            self.assertIn('class="model-actions"', page)
            self.assertIn('class="model-actions model-actions-wide"', page)
        finally:
            response.close()

    def test_frontend_css_contains_responsive_layout_guards(self):
        response = self.client.get("/static/app.css")
        try:
            css = response.get_data(as_text=True)

            self.assertIn("#chat-messages-container { display: flex; flex-direction: column;", css)
            self.assertIn(".message-bubble pre", css)
            self.assertIn("white-space: pre-wrap", css)
            self.assertIn("repeat(auto-fit, minmax(150px, 1fr))", css)
            self.assertIn(".my-button:disabled", css)
            self.assertIn("#motion-meter-panel", css)
            self.assertIn("#motion-feedback-buttons", css)
            self.assertIn("#motion-status-strip", css)
            self.assertIn("#motion-status-strip { width: min(1180px, 100%); height: 74px;", css)
            self.assertIn("grid-template-columns: minmax(420px, 1.3fr) minmax(360px, 0.9fr)", css)
            self.assertIn("#visualizer-box { width: 100%; height: 74px;", css)
            self.assertIn(".motion-sequence-indicator", css)
            self.assertIn(".motion-sequence-log", css)
            self.assertIn(".motion-sequence-entry", css)
            self.assertIn(".motion-sequence-log { width: 100%; height: 74px;", css)
            self.assertIn("grid-template-rows: 68px 58px", css)
            self.assertIn("overflow-y: auto", css)
            self.assertNotIn("@keyframes motion-sequence-scroll", css)
            self.assertIn(".motion-diagnostics-panel", css)
            self.assertIn("#sidebar-motion-indicator", css)
            self.assertIn("#handy-cylinder-indicator", css)
            self.assertIn("#handy-cylinder-range { position: absolute; left: 8px; right: 8px; top: 8%; height: 84%;", css)
            self.assertIn("#visualizer-box { width: 100%;", css)
            self.assertIn(".settings-subsection { display: flex; flex-direction: column; gap: 12px;", css)
            self.assertIn(".settings-help", css)
            self.assertIn(".settings-checkbox-line", css)
            self.assertIn(".diagnostics-output", css)
            self.assertIn(".model-actions", css)
            self.assertIn(".motion-pattern-row", css)
            self.assertIn(".motion-pattern-list", css)
            self.assertIn(".motion-feedback-history", css)
            self.assertIn("#dislike-this-move-btn", css)
            self.assertIn(".motion-pattern-weight-control", css)
            self.assertIn(".motion-pattern-feedback-reset", css)
            self.assertIn(".motion-pattern-weight-field", css)
            self.assertIn(".motion-training-workspace", css)
            self.assertIn(".motion-training-box { width: min(1540px, calc(100vw - 12px));", css)
            self.assertIn("minmax(260px, 0.62fr) minmax(760px, 1.9fr)", css)
            self.assertIn(".motion-training-status", css)
            self.assertIn(".motion-training-preview-grid", css)
            self.assertIn("flex: 1 1 auto", css)
            self.assertIn(".motion-training-preview-label", css)
            self.assertIn(".motion-training-preview-wrap", css)
            self.assertIn("height: clamp(320px, 52vh, 560px)", css)
            self.assertIn("#motion-training-original-preview-canvas", css)
            self.assertIn("#motion-training-preview-canvas", css)
            self.assertIn(".motion-backend-badge", css)
            self.assertIn(".motion-training-transform-panel", css)
            self.assertIn(".motion-training-control-section", css)
            self.assertIn(".motion-training-timing-grid", css)
            self.assertIn(".motion-training-timing-control", css)
            self.assertIn(".motion-training-icon-button", css)
            self.assertIn(".motion-training-arrow-up", css)
            self.assertIn(".motion-training-number-field", css)
            self.assertIn(".motion-training-number-stepper", css)
            self.assertIn(".motion-training-readout", css)
            self.assertIn(".motion-training-save-row", css)
            self.assertIn(".motion-training-feedback-row", css)
            self.assertIn(".setup-slider", css)
            self.assertIn(".preset-mode-stack", css)
            self.assertIn(".experimental-mode-stack", css)
            self.assertIn(".experimental-mode-section", css)
            self.assertIn(".sidebar-button.experimental", css)
            self.assertIn(".sidebar-stop-section", css)
            self.assertIn("@media (max-width: 760px)", css)
        finally:
            response.close()

    def test_frontend_js_avoids_incremental_inner_html_for_options(self):
        script = self.frontend_scripts()

        self.assertNotIn("innerHTML +=", script)
        self.assertIn("elevenLabsVoiceSelect.replaceChildren", script)
        self.assertIn("startHandyCylinderAnimation", script)
        self.assertIn("slider-container setup-slider", script)

    def test_frontend_js_polls_local_voice_status_and_serializes_playback(self):
        script = self.frontend_scripts()

        self.assertIn("localTtsStatusPolling: false", script)
        self.assertIn("async function refreshLocalTtsStatus", script)
        self.assertIn("preload_elapsed_seconds", script)
        self.assertIn("generation_elapsed_seconds", script)
        self.assertIn("audio.onended", script)
        self.assertIn("new Promise", script)

    def test_chat_messages_are_rendered_as_text_nodes(self):
        script = self.frontend_scripts()

        self.assertIn("function appendMessageText", script)
        self.assertIn("D.createTextNode", script)
        self.assertNotIn('message-bubble">${text}', script)

    def test_send_message_clears_typing_indicator_on_non_chat_statuses(self):
        script = self.frontend_scripts()

        self.assertIn("function clearTypingIndicator", script)
        self.assertIn("no_key_set", script)
        self.assertIn("message_relayed_to_active_mode", script)
        self.assertIn("addChatMessage('BOT', data.chat)", script)
        self.assertIn("data.chat_queued !== true", script)
        self.assertIn("data.chat_queued === true", script)
        self.assertIn("data.chat_queued === false", script)
        self.assertIn("await pollChatUpdates()", script)

    def test_frontend_js_handles_motion_pattern_list_controls(self):
        script = self.frontend_scripts()

        self.assertIn("function renderMotionPatterns", script)
        self.assertIn("function renderMotionBackendOptions", script)
        self.assertIn("function cylinderAnimatedDepth", script)
        self.assertIn("function positionBackendAnimatedDepth", script)
        self.assertIn("function calibratedCylinderRange", script)
        self.assertIn("function activeStrokeZone", script)
        self.assertIn("startHandyCylinderAnimation", script)
        self.assertIn("Date.now() / 1000", script)
        self.assertIn("motion_observability", script)
        self.assertIn("physical_speed", script)
        self.assertIn("physical_depth", script)
        self.assertIn("stroke_zone", script)
        self.assertNotIn("el.handyCylinderRange.style.top", script)
        self.assertIn("full_travel_mm", script)
        self.assertIn("function updateMotionMeters", script)
        self.assertIn("function updateMotionSequenceIndicator", script)
        self.assertIn("function updateMotionDiagnosticsPanel", script)
        self.assertIn("function updateActiveModeTimer", script)
        self.assertIn("function updatePauseResumeUi", script)
        self.assertIn("el.pauseResumeBtn.textContent = 'Resume/Pause'", script)
        self.assertIn("async function toggleMotionPause", script)
        self.assertIn("function handleMotionHotkey", script)
        self.assertIn("function closeSignalAvailable", script)
        self.assertIn("MediaPlayPause", script)
        self.assertIn("MediaStop", script)
        self.assertIn("SHIFT_DOUBLE_TAP_MS", script)
        self.assertIn("/toggle_motion_pause", script)
        self.assertIn("function formatClockElapsed", script)
        self.assertIn("padStart(2, '0')", script)
        self.assertIn("function formatMotionTraceTiming", script)
        self.assertIn("MOTION_SEQUENCE_LOG_LIMIT", script)
        self.assertIn("function resetMotionSequenceLog", script)
        self.assertIn("function appendMotionSequenceLogEntry", script)
        self.assertIn("function motionSequenceLogTime", script)
        self.assertIn("formatClockElapsed(state.activeModeElapsedSeconds ?? 0)", script)
        self.assertIn("state.activeModeName", script)
        self.assertIn("active_mode_elapsed_seconds", script)
        self.assertIn("function updateMemoryToggleUi", script)
        self.assertIn("async function toggleLongTermMemory", script)
        self.assertIn("/toggle_memory", script)
        self.assertIn("Memories: ${state.useLongTermMemory ? 'ON' : 'OFF'}", script)
        self.assertIn("aria-pressed", script)
        self.assertIn("motionSequenceIndicator", script)
        self.assertIn("function saveMotionFeedbackOptions", script)
        self.assertIn("/motion_feedback_options", script)
        self.assertIn("function updateHandyCylinder", script)
        self.assertIn("handyCylinderPosition", script)
        self.assertIn("/set_motion_backend", script)
        self.assertIn("/set_llm_edge_permissions", script)
        self.assertIn("Flexible position/script", script)
        self.assertIn("refreshMotionPatterns", script)
        self.assertIn("/motion_patterns", script)
        self.assertIn("motionPatternList.replaceChildren", script)
        self.assertIn("motionTrainingPatternList.replaceChildren", script)
        self.assertIn("motionPatternImportInput", script)
        self.assertIn("FormData", script)
        self.assertIn("Import failed", script)
        self.assertIn("function openMotionTrainingWorkspace", script)
        self.assertIn("motionTrainingOriginalPreviewCanvas", script)
        self.assertIn("function drawPatternPreviewCanvas", script)
        self.assertIn("function drawMotionTrainingPreview", script)
        self.assertIn("function smoothEditedPattern", script)
        self.assertIn("function harshenEditedPattern", script)
        self.assertIn("function patternTempoScale", script)
        self.assertIn("function updateMotionTrainingTimingReadouts", script)
        self.assertIn("function setEditedPatternDuration", script)
        self.assertIn("function setEditedPatternTempo", script)
        self.assertIn("function stepMotionTrainingRangeInput", script)
        self.assertIn("tempo_scale", script)
        self.assertIn("editablePatternPayload", script)
        self.assertIn("(edited)", script)
        self.assertIn("/motion_training/preview", script)
        self.assertIn("/motion_patterns/save_generated", script)
        self.assertIn("/motion_training/start", script)
        self.assertIn("/motion_training/stop", script)
        self.assertIn("sendMotionTrainingFeedback", script)
        self.assertIn("thumbs_up", script)
        self.assertIn("function createPatternWeightControl", script)
        self.assertIn("function renderMotionFeedbackHistory", script)
        self.assertIn("function resetMotionPatternFeedback", script)
        self.assertIn("function setMotionPatternWeight", script)
        self.assertIn("/motion_patterns/${encodeURIComponent(patternId)}/weight", script)
        self.assertIn("/motion_patterns/${encodeURIComponent(patternId)}/feedback/reset", script)
        self.assertIn("motion-training-number-step-up", script)
        self.assertIn("motion-training-number-step-down", script)
        self.assertIn("function dislikeLastMove", script)
        self.assertIn("/dislike_last_move", script)
        self.assertIn("/signal_edge", script)
        self.assertIn("async function startFreestyleMode", script)
        self.assertIn("/start_freestyle_mode", script)
        self.assertIn("freestyle_started", script)
        self.assertIn("Milking mode extended", script)
        self.assertIn("data.active_mode", script)
        self.assertIn("weight ${pattern.weight", script)
        self.assertIn("/set_diagnostics_levels", script)
        self.assertIn("function updateOllamaDiagnostics", script)

    def test_motion_sequence_log_module_is_extracted(self):
        motion_response = self.client.get("/static/js/motion-control.js")
        sequence_response = self.client.get("/static/js/motion/sequence-log.js")
        try:
            motion_control_script = motion_response.get_data(as_text=True)
            sequence_log_script = sequence_response.get_data(as_text=True)

            self.assertIn("from './motion/sequence-log.js'", motion_control_script)
            self.assertIn("Compatibility shim - do not extend", motion_control_script)
            self.assertIn("export { resetMotionSequenceLog, updateMotionSequenceIndicator }", motion_control_script)
            self.assertIn("export function updateMotionSequenceIndicator", sequence_log_script)
            self.assertIn("function appendMotionSequenceLogEntry", sequence_log_script)
            self.assertIn("const MOTION_SEQUENCE_LOG_LIMIT = 40", sequence_log_script)
            self.assertIn("formatClockElapsed(state.activeModeElapsedSeconds ?? 0)", sequence_log_script)
            self.assertIn("el.motionSequenceIndicator.scrollTop", sequence_log_script)
            self.assertNotIn("async function toggleMotionPause", sequence_log_script)
            self.assertNotIn("function startFreestyleMode", sequence_log_script)
        finally:
            motion_response.close()
            sequence_response.close()

    def test_motion_pause_controls_module_is_extracted(self):
        motion_response = self.client.get("/static/js/motion-control.js")
        pause_response = self.client.get("/static/js/motion/pause-controls.js")
        try:
            motion_control_script = motion_response.get_data(as_text=True)
            pause_controls_script = pause_response.get_data(as_text=True)

            self.assertIn("from './motion/pause-controls.js'", motion_control_script)
            self.assertIn("Compatibility shim - do not extend", motion_control_script)
            self.assertIn("export function bindMotionPauseControls", pause_controls_script)
            self.assertIn("export function updatePauseResumeUi", pause_controls_script)
            self.assertIn("export async function toggleMotionPause", pause_controls_script)
            self.assertIn("export function handleMotionHotkey", pause_controls_script)
            self.assertIn("const SHIFT_DOUBLE_TAP_MS = 350", pause_controls_script)
            self.assertIn("/toggle_motion_pause", pause_controls_script)
            self.assertIn("/stop_auto_mode", pause_controls_script)
            self.assertIn("/signal_edge", pause_controls_script)
            self.assertIn("MediaPlayPause", pause_controls_script)
            self.assertIn("MediaStop", pause_controls_script)
            self.assertIn("sendUserMessage('stop')", pause_controls_script)
            self.assertIn("closeMotionTrainingWorkspace", pause_controls_script)
            self.assertNotIn("function handleMotionHotkey", motion_control_script)
            self.assertNotIn("async function toggleMotionPause", motion_control_script)
            self.assertNotIn("/motion_training/preview", pause_controls_script)
            self.assertNotIn("function startFreestyleMode", pause_controls_script)
        finally:
            motion_response.close()
            pause_response.close()

    def test_motion_pattern_list_module_is_extracted(self):
        motion_response = self.client.get("/static/js/motion-control.js")
        pattern_response = self.client.get("/static/js/motion/pattern-list.js")
        try:
            motion_control_script = motion_response.get_data(as_text=True)
            pattern_list_script = pattern_response.get_data(as_text=True)

            self.assertIn("from './motion/pattern-list.js'", motion_control_script)
            self.assertIn("configureMotionPatternList({renderMotionPatterns, setMotionTrainingDetail})", motion_control_script)
            self.assertIn("Compatibility shim - do not extend", motion_control_script)
            self.assertIn("export function renderCompactMotionPatternList", pattern_list_script)
            self.assertIn("export function configureMotionPatternList", pattern_list_script)
            self.assertIn("export function formatPatternMetadata", pattern_list_script)
            self.assertIn("export async function setMotionPatternEnabled", pattern_list_script)
            self.assertIn("export async function setMotionPatternWeight", pattern_list_script)
            self.assertIn("export async function resetMotionPatternFeedback", pattern_list_script)
            self.assertIn("motionPatternList.replaceChildren", pattern_list_script)
            self.assertIn("motion-pattern-weight-control", pattern_list_script)
            self.assertIn("motion-pattern-feedback-reset", pattern_list_script)
            self.assertIn("/motion_patterns/${encodeURIComponent(patternId)}/enabled", pattern_list_script)
            self.assertIn("/motion_patterns/${encodeURIComponent(patternId)}/weight", pattern_list_script)
            self.assertIn("/motion_patterns/${encodeURIComponent(patternId)}/feedback/reset", pattern_list_script)
            self.assertNotIn("function renderCompactMotionPatternList", motion_control_script)
            self.assertNotIn("async function setMotionPatternWeight", motion_control_script)
            self.assertNotIn("/motion_training/preview", pattern_list_script)
            self.assertNotIn("async function startMotionTraining", pattern_list_script)
        finally:
            motion_response.close()
            pattern_response.close()

    def test_motion_feedback_controls_module_is_extracted(self):
        motion_response = self.client.get("/static/js/motion-control.js")
        feedback_response = self.client.get("/static/js/motion/feedback-controls.js")
        try:
            motion_control_script = motion_response.get_data(as_text=True)
            feedback_controls_script = feedback_response.get_data(as_text=True)

            self.assertIn("from './motion/feedback-controls.js'", motion_control_script)
            self.assertIn("configureMotionFeedbackControls({renderMotionPatterns})", motion_control_script)
            self.assertIn("Compatibility shim - do not extend", motion_control_script)
            self.assertIn("export function configureMotionFeedbackControls", feedback_controls_script)
            self.assertIn("export function renderMotionFeedbackHistory", feedback_controls_script)
            self.assertIn("export async function saveMotionFeedbackOptions", feedback_controls_script)
            self.assertIn("/motion_feedback_options", feedback_controls_script)
            self.assertIn("motionFeedbackAutoDisableCheckbox", feedback_controls_script)
            self.assertIn("Repeated thumbs down can disable patterns", feedback_controls_script)
            self.assertIn("Repeated thumbs down will not disable patterns", feedback_controls_script)
            self.assertIn("motionFeedbackHistory.replaceChildren", feedback_controls_script)
            self.assertIn("No recent pattern feedback", feedback_controls_script)
            self.assertNotIn("function renderMotionFeedbackHistory", motion_control_script)
            self.assertNotIn("async function saveMotionFeedbackOptions", motion_control_script)
            self.assertNotIn("/motion_training/preview", feedback_controls_script)
            self.assertNotIn("async function setMotionPatternWeight", feedback_controls_script)
        finally:
            motion_response.close()
            feedback_response.close()

    def test_motion_training_editor_module_is_extracted(self):
        motion_response = self.client.get("/static/js/motion-control.js")
        editor_response = self.client.get("/static/js/motion/training-editor.js")
        try:
            motion_control_script = motion_response.get_data(as_text=True)
            training_editor_script = editor_response.get_data(as_text=True)

            self.assertIn("from './motion/training-editor.js'", motion_control_script)
            self.assertIn("Compatibility shim - do not extend", motion_control_script)
            self.assertIn("export function patternTempoScale", training_editor_script)
            self.assertIn("export function updateMotionTrainingTimingReadouts", training_editor_script)
            self.assertIn("export function syncRangeInputsFromPattern", training_editor_script)
            self.assertIn("export function stepMotionTrainingRangeInput", training_editor_script)
            self.assertIn("export function setMotionEditStatus", training_editor_script)
            self.assertIn("export function updateMotionTrainingEditButtons", training_editor_script)
            self.assertIn("export function editablePatternPayload", training_editor_script)
            self.assertIn("export function refreshMotionTrainingDetail", training_editor_script)
            self.assertIn("export function smoothEditedPattern", training_editor_script)
            self.assertIn("export function harshenEditedPattern", training_editor_script)
            self.assertIn("export function setEditedPatternTempo", training_editor_script)
            self.assertIn("export function setEditedPatternDuration", training_editor_script)
            self.assertIn("export function remapEditedPatternRange", training_editor_script)
            self.assertIn("export function resetEditedPattern", training_editor_script)
            self.assertIn("export function drawPatternPreviewCanvas", training_editor_script)
            self.assertIn("export function drawMotionTrainingPreview", training_editor_script)
            self.assertIn("export function setMotionTrainingDetail", training_editor_script)
            self.assertIn("export function setMotionTrainingLoadingDetail", training_editor_script)
            self.assertIn("export function drawOpenMotionTrainingPreview", training_editor_script)
            self.assertIn("motionTrainingEditedPattern", training_editor_script)
            self.assertIn("motionTrainingPreviewCanvas", training_editor_script)
            self.assertIn("motionTrainingOriginalPreviewCanvas", training_editor_script)
            # Editor utilities are pure UI; route calls and the workspace
            # open/close orchestration stay in motion-control.js.
            self.assertNotIn("/motion_training/start", training_editor_script)
            self.assertNotIn("/motion_training/stop", training_editor_script)
            self.assertNotIn("/motion_training/preview", training_editor_script)
            self.assertNotIn("/motion_patterns/save_generated", training_editor_script)
            self.assertNotIn("openMotionTrainingWorkspace", training_editor_script)
            self.assertNotIn("renderMotionTrainingPatternList", training_editor_script)
            # The relocated definitions must no longer live in motion-control.js.
            self.assertNotIn("function smoothEditedPattern", motion_control_script)
            self.assertNotIn("function harshenEditedPattern", motion_control_script)
            self.assertNotIn("function setEditedPatternDuration", motion_control_script)
            self.assertNotIn("function setEditedPatternTempo", motion_control_script)
            self.assertNotIn("function remapEditedPatternRange", motion_control_script)
            self.assertNotIn("function resetEditedPattern", motion_control_script)
            self.assertNotIn("function drawPatternPreviewCanvas", motion_control_script)
            self.assertNotIn("function drawMotionTrainingPreview", motion_control_script)
            self.assertNotIn("function setMotionTrainingDetail", motion_control_script)
            self.assertNotIn("function setMotionTrainingLoadingDetail", motion_control_script)
            self.assertNotIn("function editablePatternPayload", motion_control_script)
            self.assertNotIn("function refreshMotionTrainingDetail", motion_control_script)
        finally:
            motion_response.close()
            editor_response.close()

    def test_frontend_js_is_split_into_domain_modules(self):
        response = self.client.get("/static/app.js")
        try:
            app_script = response.get_data(as_text=True)
        finally:
            response.close()

        self.assertIn("./js/settings.js", app_script)
        self.assertIn("./js/chat.js", app_script)
        self.assertIn("./js/audio.js", app_script)
        self.assertIn("./js/device-control.js", app_script)
        self.assertIn("./js/motion-control.js", app_script)
        self.assertIn("./js/setup.js", app_script)


if __name__ == "__main__":
    unittest.main()
