import unittest
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]


class InstallScriptTests(unittest.TestCase):
    def test_windows_launcher_runs_installed_virtualenv(self):
        launcher = (PROJECT_ROOT / "Run StrokeGPT-ReVibed.cmd").read_text(encoding="utf-8")
        readme = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")
        installer = (PROJECT_ROOT / "scripts" / "install_windows.ps1").read_text(encoding="utf-8")

        self.assertIn('cd /d "%~dp0"', launcher)
        self.assertIn('set "PYTHON_EXE=%~dp0.venv\\Scripts\\python.exe"', launcher)
        self.assertIn('set "STROKEGPT_OPEN_BROWSER=1"', launcher)
        self.assertIn('"%PYTHON_EXE%" app.py', launcher)
        self.assertIn("Run scripts\\install_windows.ps1 first", launcher)
        self.assertIn("pause", launcher)
        self.assertIn("Run StrokeGPT-ReVibed.cmd", installer)
        self.assertIn("Run StrokeGPT-ReVibed.cmd", readme)

    def test_windows_https_launcher_enables_lan_voice_mode(self):
        launcher = (PROJECT_ROOT / "Run StrokeGPT-ReVibed HTTPS.bat").read_text(encoding="utf-8")
        readme = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")
        installer = (PROJECT_ROOT / "scripts" / "install_windows.ps1").read_text(encoding="utf-8")

        self.assertIn('cd /d "%~dp0"', launcher)
        self.assertIn('set "PYTHON_EXE=%~dp0.venv\\Scripts\\python.exe"', launcher)
        self.assertIn('set "STROKEGPT_OPEN_BROWSER=1"', launcher)
        self.assertIn('set "STROKEGPT_HOST=0.0.0.0"', launcher)
        self.assertIn('set "STROKEGPT_PORT=5011"', launcher)
        self.assertIn('set "STROKEGPT_HTTPS=1"', launcher)
        self.assertIn('"%PYTHON_EXE%" app.py', launcher)
        self.assertIn("strokegpt-lan-ca.crt", launcher)
        self.assertIn("STROKEGPT_HTTPS_IPS", launcher)
        self.assertIn("Run StrokeGPT-ReVibed HTTPS.bat", installer)
        self.assertIn("Run StrokeGPT-ReVibed HTTPS.bat", readme)

    def test_windows_installer_prompts_for_optional_runtime_dependencies(self):
        script = (PROJECT_ROOT / "scripts" / "install_windows.ps1").read_text(encoding="utf-8")

        self.assertIn('[string]$InstallPython = "Prompt"', script)
        self.assertIn('[string]$InstallOllama = "Prompt"', script)
        self.assertIn('[string]$InstallCudaTorch = "Prompt"', script)
        self.assertIn('[string]$InstallParakeet = "Prompt"', script)
        self.assertIn('[string]$DownloadOllamaModel = "Prompt"', script)
        self.assertIn('Python.Python.3.11', script)
        self.assertIn('Install-PythonIfRequested', script)
        self.assertIn('Refresh-PathFromRegistry', script)
        self.assertIn('function Invoke-WingetInstall', script)
        self.assertIn('Winget output is hidden because its progress bar can render poorly', script)
        self.assertIn('*> $logPath', script)
        self.assertNotIn('| Out-Host', script)
        self.assertIn('$pythonInstallExitCode = Invoke-WingetInstall', script)
        self.assertIn('"install", "--id", $PythonWingetId', script)
        self.assertIn('"--accept-package-agreements", "--accept-source-agreements"', script)
        self.assertIn('"--disable-interactivity"', script)
        self.assertIn('$oldErrorActionPreference = $ErrorActionPreference', script)
        self.assertIn('$ErrorActionPreference = "SilentlyContinue"', script)
        self.assertIn("*> $null", script)
        self.assertIn("return $false", script)
        self.assertIn("$command = @($script:PythonCommand)", script)
        self.assertIn("$script:PythonCommand = @(Find-Python)", script)
        self.assertIn("Read-Host", script)
        self.assertIn('$ollamaInstallExitCode = Invoke-WingetInstall', script)
        self.assertIn('"install", "--id", "Ollama.Ollama"', script)
        self.assertIn("Default Ollama model choices", script)
        self.assertIn("VRAM capacity warning", script)
        self.assertIn('Id = "GemmaE4B"', script)
        self.assertIn('if ($ChoiceId -eq "Default")', script)
        self.assertIn("nexusriot/Gemma-4-Uncensored-HauhauCS-Aggressive:e4b", script)
        self.assertIn("nexusriot/Gemma-4-Uncensored-HauhauCS-Aggressive:e2b", script)
        self.assertIn("huihui_ai/granite4.1-abliterated:3b", script)
        self.assertIn("huihui_ai/granite4.1-abliterated:8b", script)
        self.assertIn("6.3 GB", script)
        self.assertIn("4.4 GB", script)
        self.assertIn("2.1 GB", script)
        self.assertIn("5.3 GB", script)
        self.assertIn("& $ollamaCommand pull $choice.Model", script)
        self.assertIn("https://download.pytorch.org/whl/cu128", script)
        self.assertIn("install_parakeet.ps1", script)
        self.assertIn("Legacy model download switch detected", script)

    def test_windows_updater_fast_forwards_without_model_downloads(self):
        script = (PROJECT_ROOT / "scripts" / "update_windows.ps1").read_text(encoding="utf-8")

        self.assertIn('Invoke-Git @("fetch", "origin")', script)
        self.assertIn('Invoke-Git @("merge", "--ff-only", $upstreamRef)', script)
        self.assertIn("status --porcelain --untracked-files=no", script)
        self.assertIn("-NonInteractive", script)
        self.assertIn("-InstallOllama No", script)
        self.assertIn("-InstallCudaTorch No", script)
        self.assertIn("-InstallParakeet No", script)
        self.assertIn("-DownloadOllamaModel No", script)
        self.assertIn("-UpdateParakeet", script)
        self.assertIn("[switch]$RunValidation", script)
        self.assertNotIn("ollama pull", script)

    def test_setup_verifier_checks_runtime_without_model_downloads(self):
        script = (PROJECT_ROOT / "scripts" / "verify_setup.ps1").read_text(encoding="utf-8")
        readme = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")

        self.assertIn('[string]$OllamaBaseUrl = "http://127.0.0.1:11434"', script)
        self.assertIn('[int]$Port = 5000', script)
        self.assertIn("[switch]$SkipOllama", script)
        self.assertIn("[switch]$Json", script)
        self.assertIn("Test-PythonModule", script)
        self.assertIn('"flask" -Required', script)
        self.assertIn('"requests" -Required', script)
        self.assertIn('"cryptography" -Required', script)
        self.assertIn('"elevenlabs" -Required', script)
        self.assertIn('"faster_whisper"', script)
        self.assertIn('"chatterbox.tts_turbo"', script)
        self.assertIn("Test-TorchRuntime", script)
        self.assertIn("/api/tags", script)
        self.assertIn("Test-PortAvailability", script)
        self.assertIn('Test-WritableFolder "user-data"', script)
        self.assertIn('Test-WritableFolder "diagnostics-folder"', script)
        self.assertIn('Test-WritableFolder "voice-samples"', script)
        self.assertIn("ConvertTo-Json", script)
        self.assertNotIn("ollama pull", script)
        self.assertNotIn("from_pretrained", script)
        self.assertIn(".\\scripts\\verify_setup.ps1", readme)

    def test_windows_bootstrap_downloads_or_clones_repo_and_runs_installer(self):
        script = (PROJECT_ROOT / "scripts" / "bootstrap_windows.ps1").read_text(encoding="utf-8")
        readme = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")

        self.assertIn('Git.Git', script)
        self.assertIn('git clone', script)
        self.assertIn('archive/refs/heads/master.zip', script)
        self.assertIn('Expand-Archive', script)
        self.assertIn('install_windows.ps1', script)
        self.assertIn('Administrator PowerShell is not required', script)
        self.assertIn('Documents")) "StrokeGPT-ReVibed"', script)
        self.assertIn('raw.githubusercontent.com/mapledaemon/StrokeGPT-ReVibed/master/scripts/bootstrap_windows.ps1', readme)
        self.assertIn('Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force; $bootstrap = Join-Path $env:TEMP "strokegpt-bootstrap.ps1"; Invoke-WebRequest', readme)
        self.assertIn('; powershell.exe -NoProfile -ExecutionPolicy Bypass -File $bootstrap', readme)
        self.assertIn('no admin needed', readme)

    def test_readme_documents_lan_access(self):
        readme = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")
        lan_doc = (PROJECT_ROOT / "docs" / "lan_https.md").read_text(encoding="utf-8")

        self.assertIn("## Use from another device on LAN", readme)
        self.assertIn("docs/lan_https.md", readme)
        self.assertIn("https://<PC-LAN-IP>:5011", readme)
        self.assertIn("Run StrokeGPT-ReVibed HTTPS.bat", readme)
        self.assertNotIn("STROKEGPT_HTTPS_IPS", readme)
        self.assertNotIn("user_data/https/strokegpt-lan-ca.crt", readme)
        self.assertIn("STROKEGPT_HOST=\"0.0.0.0\"", lan_doc)
        self.assertIn("STROKEGPT_PORT=\"5011\"", lan_doc)
        self.assertIn("STROKEGPT_HTTPS=\"1\"", lan_doc)
        self.assertIn("https://<PC-LAN-IP>:5011", lan_doc)
        self.assertIn("user_data/https/", lan_doc)
        self.assertIn("strokegpt-lan-ca.crt", lan_doc)
        self.assertIn("STROKEGPT_SSL_CERT", lan_doc)
        self.assertIn("STROKEGPT_SSL_KEY", lan_doc)
        self.assertIn("STROKEGPT_HTTPS_IPS", lan_doc)
        self.assertIn("STROKEGPT_HTTPS_CERT_HELPER", lan_doc)
        self.assertIn("STROKEGPT_HTTPS_CERT_PORT", lan_doc)
        self.assertIn("Android Chrome certificate helper", lan_doc)
        self.assertIn("Mobile Chrome is stricter than Firefox", lan_doc)
        self.assertIn("Do not port-forward StrokeGPT", lan_doc)
        self.assertIn("Mobile browser microphone capture needs HTTPS", readme)

    def test_ollama_gpu_docs_explain_windows_vulkan_user_environment(self):
        readme = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")
        doc = (PROJECT_ROOT / "docs" / "ollama_gpu.md").read_text(encoding="utf-8")

        self.assertIn("docs/ollama_gpu.md", readme)
        self.assertIn("Default installer model choices", doc)
        self.assertIn("nexusriot/Gemma-4-Uncensored-HauhauCS-Aggressive:e4b", doc)
        self.assertIn("### Windows Vulkan setup", doc)
        self.assertIn("user environment variable", doc)
        self.assertIn("setx OLLAMA_VULKAN 1", doc)
        self.assertIn("Edit environment variables for your account", doc)
        self.assertIn("reg delete HKCU\\Environment /v OLLAMA_VULKAN /f", doc)
        self.assertIn("GGML_VK_VISIBLE_DEVICES", doc)

    def test_parakeet_installer_defaults_to_blackwell_capable_pytorch_wheels(self):
        script = (PROJECT_ROOT / "scripts" / "install_parakeet.ps1").read_text(encoding="utf-8")

        self.assertIn("function Test-PythonCommand", script)
        self.assertIn('$ErrorActionPreference = "SilentlyContinue"', script)
        self.assertIn('Test-PythonCommand @("py", "-3.11") -MinimumMinor 11', script)
        self.assertIn('Test-PythonCommand @("python")', script)
        self.assertIn("$command = @($script:PythonCommand)", script)
        self.assertIn("$script:PythonCommand = @(Find-Python)", script)
        self.assertIn('$TorchIndexUrl = "https://download.pytorch.org/whl/cu128"', script)
        self.assertNotIn("/whl/cu121", script)
        self.assertIn('"--upgrade", "--force-reinstall", "--index-url", $TorchIndexUrl, "torch", "torchvision", "torchaudio"', script)
        self.assertIn('"--upgrade", "--force-reinstall", "--no-deps", "--index-url", $TorchIndexUrl, "torch", "torchvision", "torchaudio"', script)

    def test_parakeet_installer_preserves_nemo_dependency_pins(self):
        script = (PROJECT_ROOT / "scripts" / "install_parakeet.ps1").read_text(encoding="utf-8")
        requirements = (PROJECT_ROOT / "requirements-parakeet.txt").read_text(encoding="utf-8")

        self.assertIn("fsspec==2024.12.0", requirements)
        self.assertIn("setuptools>=79.0.0,<82", requirements)
        self.assertIn("protobuf>=6.31.1,<7", requirements)
        self.assertIn("function Invoke-ParakeetPython", script)
        self.assertIn("function Test-ParakeetProtobufRuntime", script)
        self.assertIn('$env:PYTHONNOUSERSITE = "1"', script)
        self.assertIn("Parakeet Python command failed", script)
        self.assertIn('"--upgrade", "--force-reinstall", "--no-cache-dir", "fsspec==2024.12.0", "setuptools>=79.0.0,<82", "protobuf>=6.31.1,<7"', script)
        self.assertIn("import google.protobuf", script)
        self.assertIn("import onnx", script)
        self.assertIn("Checking ONNX protobuf runtime compatibility", script)
        self.assertIn('"-m", "pip", "check"', script)


if __name__ == "__main__":
    unittest.main()
